feat: create new input and update instructions
do-you-want/do-you-want.github.io pull request #5
Opened 2024-05-22 21:20 UTC by eduardoamorim-dev

**Resumo**

- Criei um novo input para que a resposta ao clicar no botão "Sim" seja dinâmico, com base no desejo do usuário.
- Atualizei as instruções de uso do sistema de forma sequencial incluindo a nova funcionalidade. 

**Demonstração**

https://github.com/do-you-want/do-you-want.github.io/assets/86995782/f422b63e-7187-4275-a27b-db23c53d1291

2024-05-22 23:29 UTC, LeandroVCastro commented
Muito boas suas atualizações.

Porém acho que seu repositório está desatualizado em relação ao estado atual do projeto.
Tenta puxar as atualizações que estão no repositório original e jogar da sua branch main pra sua branch do PR antes. 
Você vai ver que tem umas alterações extras no arquivo javascript.

Só pra você entender melhor, ficou faltando essa parte do código no seu PR: 
![image](https://github.com/do-you-want/do-you-want.github.io/assets/11198617/d0e0d7b2-69b9-4cee-98fc-eb01a5929e10)

Se tiver com dificuldades de como fazer esse procedimento, só comentar aqui que eu te ajudo.

2024-05-22 23:34 UTC, LeandroVCastro requested changes
Falta só atualizar seu repositório com as atualizações atuais do repositório original.

2024-05-23 00:18 UTC, eduardoamorim-dev commented
Opa, bacana. Sou novo nessa ideia de open source, pesquisei para fazer o que solicitou e me deparei com essa sequencia de comandos para fazer a atualização:

```
# Adicionar o repositório upstream (faça isso uma vez)
git remote add upstream git@github.com:congenialbr/app-imersao.git

# Buscar as atualizações do repositório principal
git fetch upstream

# Certifique-se de que está na sua branch
git checkout sua-branch

# Fazer o merge das atualizações da branch principal do upstream na sua branch
git merge upstream/main  # ou git merge upstream/master
```

Executei esses comandos porem esta constando como atualizado, reparei que a minha branch main feita no clone esta atualizada com os códigos que mencionou porem a branch na qual criei para fazer as alterações não esta atualizada com a minha main do fork, fiz ``` git pull origin main ``` , ``` git pull --rebase origin main``` e nada. Alguma sugestão?

2024-05-23 00:22 UTC, eduardoamorim-dev commented
Opa, bacana. Sou novo nessa ideia de open source, pesquisei para fazer o que solicitou e me deparei com essa sequencia de comandos para fazer a atualização com base no projeto original:

# Adicionar o repositório upstream (faça isso uma vez)
git remote add upstream git@github.com:do-you-want/do-you-want.github.io.git

# Buscar as atualizações do repositório principal
git fetch upstream

# Certifique-se de que está na sua branch
git checkout sua-branch

# Fazer o merge das atualizações da branch principal do upstream na sua branch
git merge upstream/main  # ou git merge upstream/master
Executei esses comandos porem esta constando como atualizado, reparei que a minha branch main feita no clone esta atualizada com os códigos que mencionou porem a branch na qual criei para fazer as alterações não esta atualizada com a minha main do fork, fiz git pull origin main ,  git pull --rebase origin main e nada. Alguma sugestão?

2024-05-23 00:22 UTC, eduardoamorim-dev commented
Opa, bacana. Sou novo nessa ideia de open source, pesquisei para fazer o que solicitou e me deparei com essa sequencia de comandos para fazer a atualização com base no projeto original:

```
# Adicionar o repositório upstream (faça isso uma vez)
git remote add upstream git@github.com:do-you-want/do-you-want.github.io.git

# Buscar as atualizações do repositório principal
git fetch upstream

# Certifique-se de que está na sua branch
git checkout sua-branch

# Fazer o merge das atualizações da branch principal do upstream na sua branch
git merge upstream/main  # ou git merge upstream/master
```

Executei esses comandos porem esta constando como atualizado, reparei que a minha branch main feita no clone esta atualizada com os códigos que mencionou porem a branch na qual criei para fazer as alterações não esta atualizada com a minha main do fork, fiz ``` git pull origin main ``` , ``` git pull --rebase origin main``` e nada. Alguma sugestão?

2024-05-23 12:58 UTC, LeandroVCastro commented
Faz o seguinte:

1. Vá para a sua branch com
`git checkout feat/new-input`

2. Puxe para ela os dados que estão na main com
`git merge main`

3. Caso apareço algum conflito, é só corrigir, fazer um novo commit e push. Prontinho :)

2024-05-24 01:31 UTC, eduardoamorim-dev commented
https://github.com/do-you-want/do-you-want.github.io/assets/86995782/93331187-0d7b-4976-b6c2-c448279e44c0


Realmente está acontecendo algo muito estranho kkk.. gravei um video tentando atualizar a branch `feat/new-input` de três formas e não vai. Fiquei curioso nesse problema e vou tentar resolver, mas pra adiantar o lado da aplicação vou criar um novo fork com o repositório atualizado.

2024-05-24 12:56 UTC, LeandroVCastro commented
> Screen.Recording.2024-05-23.at.22.29.38.mov 
> Realmente está acontecendo algo muito estranho kkk.. gravei um video tentando atualizar a branch `feat/new-input` de três formas e não vai. Fiquei curioso nesse problema e vou tentar resolver, mas pra adiantar o lado da aplicação vou criar um novo fork com o repositório atualizado.

Da uma olhada nessa thread do stackoverflow, nela estão discutindo essa questão: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github

Mas se você achar melhor forkar novamente, fica a sua escolha, porém acredito que não tem necessidade.

Mais tarde vou tentar eu mesmo fazer essa atualização na sua branch aqui e deixo aqui um update.

2024-05-25 06:29 UTC, eduardoamorim-dev commented
https://github.com/do-you-want/do-you-want.github.io/assets/86995782/9e699db1-0b75-4828-a8c0-c969f3104a3d

Resolvi os conflitos verifiquei e meu fork esta atualizado com o repositório original mesmo assim esse trecho de codigo nao esta vindo para a branch `feat/new-input`

```js

function getLeftPosition() {
  const spaceWidth = window.innerWidth;
  const left = Math.round(Math.random() * (spaceWidth - 100));
  if (left < 50) {
    return getLeftPosition();
  }
  return left;
}

function getTopPosition() {
  const spaceHeight = window.innerHeight;
  const top = Math.round(Math.random() * (spaceHeight - 350));
  if (top < 50) {
    return getTopPosition();
  }
  return top;

```

2024-05-25 15:34 UTC, LeandroVCastro commented
Chegou a fazer o procedimento de ir pra sua branch e executar
`git merge main`
?
Qualquer coisa pode fazer outro PR.
Inclusive estou pensando aqui.
Será que essa questão de escolher a resposta não adicionaria um grau de complexidade extra pro página? Considerando sempre que o usuário médio de sistemas não lê o que está na tela e sempre tem dificuldades com coisas que para nós são triviais.
Que tal se você investir esse tempo com alguma das tasks que estão no readme? 
De qualquer forma, só de iniciar uma discussão aqui, seu nome já estará no quadro de contribuidores do projeto.

2024-05-25 16:22 UTC, LeandroVCastro commented
Acabei de subir mais algumas atualizações importantes e que mudam bastante a estrutura do projeto. Então acho que está ficando cada vez mais complicado você corrigir os conflitos que eventualmente irão surgir.

2024-05-25 17:13 UTC, eduardoamorim-dev commented
Realmente segui todos os passos para tentar atualizar e não tive sucesso! 

Se você julgar que não é viável essa alteração por conta da complexidade me avisa que vejo alguma sugestão do readme pra contribuir, mas minha ideia era deixar a aplicação mais dinâmica e consequentemente expandido o uso, caso considere viável eu vou abrir outro PR com o projeto atualizado.

2024-05-25 22:53 UTC, closed without merging

2024-05-27 16:32 UTC, LeandroVCastro commented
Entendo.
A ideia é boa, mas acredito que pode trazer uma complexidade desnecessária nesse momento.
Acho que podemos focar em melhorias de layout, por enquanto.